function theta=rushejiao(delta,phi,beta,gamma,omega)
a=sin(delta).*(sin(phi).*cos(beta)-cos(phi).*sin(beta).*cos(gamma))+...
    cos(delta).*cos(omega).*(cos(phi).*cos(beta)+sin(phi).*sin(beta).*cos(gamma))+...
    cos(delta).*sin(beta).*sin(gamma).*sin(omega);
theta=acos(a);